name: CI - Test Coverage
on: [push]
jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Tests
        run: npm run test:coverage
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
