name: CI - Test Coverage
on: [push]
jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Tests
        run: npm run test:cov
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
