name: CI - Test Coverage
on:
  pull_request:
jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Tests
        run: npm run test:cov
      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
