name: Determine NPM Version newversion Type

on:
  push:
    branches:
      - main

jobs:
  determine-newversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo GITHUB_EVENT_PATH
