name: Determine NPM Version newversion Type

on:
  push:
    branches:
      - main

jobs:
  determine-newversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat $GITHUB_EVENT_PATH
      - run: sudo apt-get install jq
      - run: jq --help
