name: Determine NPM Version newversion Type

env:
  NEWVERSION: patch

on:
  push:
    branches:
      - main

jobs:
  determine-newversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: echo $NEWVERSION
      - run: cat $GITHUB_EVENT_PATH
      - run: jq --help
      - run: ls -al
      - run: node .github/workflows/test.js
      # https://stackoverflow.com/a/57969570/14986948
      - run: echo "NEWVERSION=$(echo "feat")" >> $GITHUB_ENV
      - run: echo $NEWVERSION
