name: Serverless Deploy Main

on:
  push:
    branches:
      - 'main'
      - 'develop'
  workflow_dispatch:

jobs:
  matrix_prep:
    name: Matrix Prep
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')  
          matrix=$(jq --arg branchName "$branchName" 'map( 
              . | select((.runOn==$branchName) or (.runOn=="always"))
          )' matrix.json)                
          echo "matrix={\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT
  print:
    name: Print Matrix Variables
    needs: matrix_prep
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}

    steps:
      - name: Print variables
        run: |
          echo "Stage: ${{ matrix.stage }}"
