# This is a workflow to test how servers act between jobs.
# Questions:
# 1. if I install node and use the same server version is node still avaliable?
# A1. No node happens to be avaliable but if you install not 17 you can see in the second machine the version is still 16.

name: Persistance Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: node -v
